-- +goose Up

CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_name" VARCHAR(20) NOT NULL UNIQUE,
	"email" VARCHAR(254) NOT NULL UNIQUE,
	"created_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	"updated_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	"magic_link" VARCHAR(32),
	PRIMARY KEY("id")
);

-- +goose Down

DROP TABLE "users";
