-- +goose Up

CREATE TABLE IF NOT EXISTS "recurring_themes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"created_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	"updated_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	"theme" TEXT NOT NULL UNIQUE,
	"user_id" INTEGER NOT NULL,
	"theme_status" VARCHAR(8) NOT NULL,
	"decline_reason" TEXT,
	PRIMARY KEY("id")
);

-- +goose Down

DROP TABLE "recurring_themes";
