-- +goose Up

CREATE TABLE IF NOT EXISTS "episode_references" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"video_id" TEXT NOT NULL,
	"time_range" TEXT,
	"recurring_theme_id" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	"updated_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	PRIMARY KEY("id")
);

-- +goose Down

DROP TABLE "episode_references";
