-- +goose Up

CREATE TABLE IF NOT EXISTS "bingo_card_cells" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"card_id" VARCHAR(255) NOT NULL,
	"recurring_theme_id" INTEGER NOT NULL,
	"x" INTEGER NOT NULL,
	"y" INTEGER NOT NULL,
	"selected" BOOLEAN NOT NULL DEFAULT FALSE,
	"user_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

-- +goose Down

DROP TABLE "bingo_card_cells";
