services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.1-alpine3.18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      busybox:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  busybox:
    image: busybox
    command: ["sh", "-c", "chown -R 5050:0 /tmp/pgadmin_data"]
    volumes:
      - ./pgadmin_data:/tmp/pgadmin_data
    restart: no
