services:
  api:
    container_name: api
    ports:
      - "4000:4000"
    environment:
      DATABASE_URI: ${DATABASE_URI}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    volumes:
      - ./backend:/app

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    ports:
      - "12345:12345"
    volumes:
      - ./logs/configs/config.alloy:/etc/alloy/config.alloy
      - ./logs/alloy/data:/var/lib/alloy/data
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./logs/loki:/loki
      - ./logs/configs/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      busybox:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      loki:
        condition: service_healthy
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        EOF
        /run.sh

  busybox:
    image: busybox
    container_name: busybox
    entrypoint: ["sh", "/scripts/dir_permission.sh"]
    volumes:
      - ./logs/scripts/dir_permission.sh:/scripts/dir_permission.sh:ro
      - ./logs/grafana:/tmp/grafana
      - ./logs/loki:/tmp/loki
    restart: no
