// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BingoCardCell struct {
	ID               int32
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	CardID           string
	RecurringThemeID int32
	X                int32
	Y                int32
	Selected         bool
	UserID           int32
}

type EpisodeReference struct {
	ID               int32
	VideoID          string
	TimeRange        pgtype.Text
	RecurringThemeID int32
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type RecurringTheme struct {
	ID            int32
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Theme         string
	UserID        int32
	ThemeStatus   string
	DeclineReason pgtype.Text
}

type User struct {
	ID        int32
	UserName  string
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	MagicLink pgtype.Text
}
