// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users(id, user_name, email, created_at, updated_at, magic_link, magic_link_created_at)
VALUES (
	gen_random_uuid(),
	$1,
	$2,
	NOW(),
	NOW(),
	$3,
	$4
	)
RETURNING id, user_name, email, created_at, updated_at, magic_link, magic_link_created_at
`

type CreateUserParams struct {
	UserName           string
	Email              string
	MagicLink          pgtype.Text
	MagicLinkCreatedAt pgtype.Timestamp
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserName,
		arg.Email,
		arg.MagicLink,
		arg.MagicLinkCreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MagicLink,
		&i.MagicLinkCreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, user_name, email, created_at, updated_at, magic_link, magic_link_created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MagicLink,
		&i.MagicLinkCreatedAt,
	)
	return i, err
}

const insertMagicLink = `-- name: InsertMagicLink :one

UPDATE users
SET updated_at = now(), magic_link = $2, magic_link_created_at = now()
WHERE email = $1
RETURNING id, user_name, email, created_at, updated_at, magic_link, magic_link_created_at
`

type InsertMagicLinkParams struct {
	Email     string
	MagicLink pgtype.Text
}

func (q *Queries) InsertMagicLink(ctx context.Context, arg InsertMagicLinkParams) (User, error) {
	row := q.db.QueryRow(ctx, insertMagicLink, arg.Email, arg.MagicLink)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MagicLink,
		&i.MagicLinkCreatedAt,
	)
	return i, err
}
