CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_name" VARCHAR(20) NOT NULL UNIQUE,
	"email" VARCHAR(254) NOT NULL UNIQUE,
	"created_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	"updated_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	"magic_link" VARCHAR(32),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "recurring_themes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"created_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	"updated_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	"theme" TEXT NOT NULL UNIQUE,
	"user_id" INTEGER NOT NULL,
	"theme_status" VARCHAR(8) NOT NULL,
	"decline_reason" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "episode_reference" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"video_id" TEXT NOT NULL,
	"time_range" TEXT,
	"recurring_theme_id" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	"updated_at" TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "bingo_card_cells" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"card_id" VARCHAR(255) NOT NULL,
	"recurring_theme_id" INTEGER NOT NULL,
	"x" INTEGER NOT NULL,
	"y" INTEGER NOT NULL,
	"selected" BOOLEAN NOT NULL DEFAULT FALSE,
	"user_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);



ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "recurring_themes"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "episode_reference"
ADD FOREIGN KEY("recurring_theme_id") REFERENCES "recurring_themes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bingo_card_cells"
ADD FOREIGN KEY("recurring_theme_id") REFERENCES "recurring_themes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bingo_card_cells"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
